live_config_reload = true

[bell]
duration = 0

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xa40e26"
index = 17

[colors.bright]
black = "0x57606a"
blue = "0x218bff"
cyan = "0x3192aa"
green = "0x1a7f37"
magenta = "0xa475f9"
red = "0xa40e26"
white = "0x8c959f"
yellow = "0x633c01"

[colors.cursor]
cursor = "#4FFF33"
text = "CellForeground"

[colors.normal]
black = "0x24292f"
blue = "0x0969da"
cyan = "0x1b7c83"
green = "0x116329"
magenta = "0x8250df"
red = "0xcf222e"
white = "0x6e7781"
yellow = "0x4d2d00"

[colors.primary]
background = "0xffffff"
foreground = "0x0E1116"

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0
offset = { x = 1, y = 1 }

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "SemiBold Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = '''\,│`|:"' ()[]{}<>	'''

[shell]
args = ["-NoLogo"]
program = "powershell"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 20
y = 20
