" colorscheme Atelier_Cavelight
colorscheme stackoverflow
set bg=light
if has("win32")
  " set guifont=Consolas:h12
  set guifont=JetBrainsMonoNL_NFM_ExtraLight:h10:W200:cANSI:qDRAFT
  set guioptions=gmtTlar
endif
set mouse=nvi
set mousehide
set columns=130 lines=35
set nocul
set foldcolumn=3
set signcolumn=yes
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
highlight clear signcolumn
highlight clear foldcolumn
" vim:ft=vim:nowrap:sw=2:ts=2:sts=2:nobackup:noundofile
